from __future__ import annotations

import uuid
from pathlib import Path

NAMESPACE = uuid.NAMESPACE_URL

INCLUDE_PREFIXES = [
    "smk ", "smjk ", "sbp ", "mrsm ",
    "sm sains", "sm teknik", "sm agama", "sma ",
    "kolej vokasional ",
    "sekolah menengah",
    "sm ",
]

EXCLUDE_PREFIXES = [
    "sk ", "srk", "srjk", "sjk",
    "sekolah rendah", "sekolah kebangsaan ",
    "tadika", "tabika", "kemas", "taska",
]

OUTPUT_PATH = (
    Path(__file__).parent.parent
    / "backend/src/main/resources/db/migration/V7__seed_schools_malaysia.sql"
)

V3_DELETE_IDS = [
    "a1b2c3d4-0000-0000-0000-000000000001",  # SK Damansara Jaya  (primary)
    "a1b2c3d4-0000-0000-0000-000000000003",  # SK Ara Damansara   (primary)
    "a1b2c3d4-0000-0000-0000-000000000004",  # SK Taman Megah     (primary)
]


def is_secondary(name: str) -> bool:
    """Return True if name matches a Malaysian secondary school type."""
    n = name.strip().lower()
    if not n:
        return False
    for prefix in EXCLUDE_PREFIXES:
        if n.startswith(prefix):
            return False
    for prefix in INCLUDE_PREFIXES:
        if n.startswith(prefix):
            return True
    return False


def extract_coords(element: dict) -> tuple[float, float] | None:
    """Return (lat, lng) from an OSM element dict, or None if coordinates are absent."""
    if element["type"] == "node":
        lat = element.get("lat")
        lng = element.get("lon")
    else:
        center = element.get("center", {})
        lat = center.get("lat")
        lng = center.get("lon")
    if lat is None or lng is None:
        return None
    return lat, lng


from datetime import date


def make_school_id(name: str) -> str:
    """Deterministic UUID5 keyed on school name — stable across re-runs."""
    return str(uuid.uuid5(NAMESPACE, f"isujana:school:{name}"))


def process(elements: list[dict]) -> list[dict]:
    """Filter, deduplicate, and sort OSM elements into school dicts."""
    seen: set[tuple] = set()
    schools: list[dict] = []
    for el in elements:
        name = el.get("tags", {}).get("name", "").strip()
        if not name or not is_secondary(name):
            continue
        coords = extract_coords(el)
        if coords is None:
            continue
        lat, lng = coords
        key = (name, round(lat, 4), round(lng, 4))
        if key in seen:
            continue
        seen.add(key)
        schools.append({"name": name, "lat": lat, "lng": lng})
    schools.sort(key=lambda s: s["name"])
    return schools


def write_sql(schools: list[dict], path: Path) -> None:
    """Write Flyway-compatible SQL migration to path."""
    delete_ids = ",\n".join(f"    '{sid}'" for sid in V3_DELETE_IDS)
    rows = [
        f"    ('{make_school_id(s['name'])}', '{s['name'].replace(chr(39), chr(39)*2)}', {s['lat']}, {s['lng']})"
        for s in schools
    ] or ["    -- (no schools generated)"]

    sql = (
        f"-- Generated by scripts/seed_schools.py on {date.today()} — do not edit by hand.\n"
        f"-- Source: OpenStreetMap Overpass API (amenity=school, Malaysia, secondary only).\n"
        f"\n"
        f"DELETE FROM schools WHERE id IN (\n"
        f"{delete_ids}\n"
        f");\n"
        f"\n"
        f"INSERT INTO schools (id, name, lat, lng) VALUES\n"
        + ",\n".join(rows) + "\n"
        f"ON CONFLICT (id) DO NOTHING;\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(sql, encoding="utf-8")
