from __future__ import annotations

from datetime import date
import uuid
from pathlib import Path

import requests

NAMESPACE = uuid.NAMESPACE_URL

INCLUDE_PREFIXES = [
    "smk ", "smjk ", "sbp ", "mrsm ",
    "sm sains", "sm teknik", "sm agama", "sma ",
    "kolej vokasional ",
    "sekolah menengah",
    "sm ",
]

EXCLUDE_PREFIXES = [
    "sk ", "srk", "srjk", "sjk",
    "sekolah rendah", "sekolah kebangsaan ",
    "tadika", "tabika", "kemas", "taska",
]

OUTPUT_PATH = (
    Path(__file__).parent.parent
    / "backend/src/main/resources/db/migration/V7__seed_schools_malaysia.sql"
)

V3_DELETE_IDS = [
    "a1b2c3d4-0000-0000-0000-000000000001",  # SK Damansara Jaya  (primary)
    "a1b2c3d4-0000-0000-0000-000000000003",  # SK Ara Damansara   (primary)
    "a1b2c3d4-0000-0000-0000-000000000004",  # SK Taman Megah     (primary)
]

OVERPASS_URL = "https://overpass-api.de/api/interpreter"
OVERPASS_MIRRORS = [
    "https://overpass-api.de/api/interpreter",
    "https://overpass.kumi.systems/api/interpreter",
    "https://maps.mail.ru/osm/tools/overpass/api/interpreter",
]
OVERPASS_QUERY = """
[out:json][timeout:120];
area["ISO3166-1"="MY"][admin_level=2]->.malaysia;
(
  nwr["amenity"="school"](area.malaysia);
);
out center tags;
"""


def is_secondary(name: str) -> bool:
    """Return True if name matches a Malaysian secondary school type."""
    n = name.strip().lower()
    if not n:
        return False
    for prefix in EXCLUDE_PREFIXES:
        if n.startswith(prefix):
            return False
    for prefix in INCLUDE_PREFIXES:
        if n.startswith(prefix):
            return True
    return False


def extract_coords(element: dict) -> tuple[float, float] | None:
    """Return (lat, lng) from an OSM element dict, or None if coordinates are absent."""
    if element["type"] == "node":
        lat = element.get("lat")
        lng = element.get("lon")
    else:
        center = element.get("center", {})
        lat = center.get("lat")
        lng = center.get("lon")
    if lat is None or lng is None:
        return None
    return lat, lng


def make_school_id(name: str) -> str:
    """Deterministic UUID5 keyed on school name — stable across re-runs."""
    return str(uuid.uuid5(NAMESPACE, f"isujana:school:{name}"))


def process(elements: list[dict]) -> list[dict]:
    """Filter, deduplicate, and sort OSM elements into school dicts."""
    seen: set[tuple] = set()
    schools: list[dict] = []
    for el in elements:
        name = el.get("tags", {}).get("name", "").strip()
        if not name or not is_secondary(name):
            continue
        coords = extract_coords(el)
        if coords is None:
            continue
        lat, lng = coords
        key = (name, round(lat, 4), round(lng, 4))
        if key in seen:
            continue
        seen.add(key)
        schools.append({"name": name, "lat": lat, "lng": lng})
    schools.sort(key=lambda s: s["name"])
    return schools


def write_sql(schools: list[dict], path: Path) -> None:
    """Write Flyway-compatible SQL migration to path."""
    delete_ids = ",\n".join(f"    '{sid}'" for sid in V3_DELETE_IDS)

    rows = [
        f"    ('{make_school_id(s['name'])}', '{s['name'].replace(chr(39), chr(39)*2)}', {s['lat']}, {s['lng']})"
        for s in schools
    ]

    insert_block = (
        f"INSERT INTO schools (id, name, lat, lng) VALUES\n"
        + ",\n".join(rows) + "\n"
        + "ON CONFLICT (id) DO NOTHING;\n"
    ) if rows else ""

    sql = (
        f"-- Generated by scripts/seed_schools.py on {date.today()} — do not edit by hand.\n"
        f"-- Source: OpenStreetMap Overpass API (amenity=school, Malaysia, secondary only).\n"
        f"\n"
        f"DELETE FROM schools WHERE id IN (\n"
        f"{delete_ids}\n"
        f");\n"
    ) + (f"\n{insert_block}" if insert_block else "")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(sql, encoding="utf-8")


def fetch_schools() -> list[dict]:
    """Query OSM Overpass API; tries multiple mirrors and retries on 429/406."""
    import time
    print("Querying Overpass API... (this may take 30-60s)")
    headers = {
        "Content-Type": "application/x-www-form-urlencoded",
        "Accept": "application/json",
        "User-Agent": "ISujanaSchoolSeeder/1.0 (educational project)",
    }
    for mirror in OVERPASS_MIRRORS:
        print(f"Trying mirror: {mirror}")
        for attempt in range(2):
            try:
                resp = requests.post(
                    mirror,
                    data=f"data={requests.utils.quote(OVERPASS_QUERY)}",
                    headers=headers,
                    timeout=180,
                )
                if resp.status_code == 429 and attempt == 0:
                    print("Rate limited — waiting 30 s before retry...")
                    time.sleep(30)
                    continue
                if resp.status_code in (406, 429, 500, 502, 503, 504) and attempt == 0:
                    print(f"HTTP {resp.status_code} — waiting 10 s before retry...")
                    time.sleep(10)
                    continue
                resp.raise_for_status()
                elements = resp.json()["elements"]
                print(f"Fetched {len(elements)} elements.")
                return elements
            except requests.exceptions.RequestException as e:
                if attempt == 0:
                    print(f"Error: {e} — retrying...")
                    time.sleep(10)
                else:
                    print(f"Mirror {mirror} failed: {e}")
                    break
    raise RuntimeError("All Overpass API mirrors failed.")


if __name__ == "__main__":
    elements = fetch_schools()
    schools = process(elements)
    print(f"After filter + dedup: {len(schools)} secondary schools.")
    write_sql(schools, OUTPUT_PATH)
    print(f"Written: {OUTPUT_PATH}")
